spring.datasource.url=jdbc:postgresql://localhost:5432/onlineshopping
spring.datasource.username=postgres
spring.datasource.password=marina812005

spring.jpa.hibernate.ddl-auto=update
# prints SQL queries in the console
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

server.port=8085

# JWT secret# a 256-bit (or longer) secret 
jwt.secret=MzJiYXNlNjRieXRlc2VjcmV0Zm9yZG9ub3RfcmVhbA==

# expiration time in ms (e.g., 10 hours)
jwt.expiration-ms=36000000
